# -*- coding: utf-8 -*-
"""CodePark3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHihFyxwmoA2MhP-hfxaWHaWbU1BknTh
"""

# Declaraçaõ das variáveis (Não obrigatório em python, porém é boa prática)
n_andar:int = 0

# Usuário insere o número de andares
n_andar = int(input("Informa o número de andares: "))
# Inicia a impressão dos número
for i in range(n_andar+1):
  # Se for 0 é térreo
  if i == 0:
    print("Térreo")
    continue
  # 3º Se o número for 13 pule-o
  elif i == 13:
    continue
  # Senão, imprima-o
  else:
    print(i)